timeout: 0
serial: yes
serial_baudrate: 115200
verbose: yes

/AxiomOS
    protocol: limine
    path: boot():/boot/AxiomOS.elf
    module_path: boot():/boot/phase11_launcher.elf
    module_string: phase11-launcher
    module_path: boot():/boot/phase11_demo.elf
    module_string: phase11-demo
    module_path: boot():/boot/phase12_demo.elf
    module_string: phase12-demo
    module_path: boot():/boot/phase13_demo.elf
    module_string: phase13-demo
    module_path: boot():/boot/axiomsh.elf
    module_string: phase14-shell
    module_path: boot():/boot/phase15_demo.elf
    module_string: phase15-demo
    module_path: boot():/boot/phase15_sleeper.elf
    module_string: phase15-sleeper
    module_path: boot():/boot/phase19_demo.elf
    module_string: phase19-demo
    module_path: boot():/boot/phase20_demo.elf
    module_string: phase20-demo
    module_path: boot():/boot/phase20_wx.elf
    module_string: phase20-wx

    module_path: boot():/boot/schedbench.elf
    module_string: phase21-schedbench
    module_path: boot():/boot/ipcdemo.elf
    module_string: phase22-ipcdemo
    module_path: boot():/boot/ipc-peer.elf
    module_string: phase22-ipc-peer
    module_path: boot():/boot/gfxdemo.elf
    module_string: phase23-gfxdemo
    module_path: boot():/boot/ifconfig.elf
    module_string: phase24-ifconfig
    module_path: boot():/boot/ping.elf
    module_string: phase24-ping
    module_path: boot():/boot/dnslookup.elf
    module_string: phase24-dnslookup
    module_path: boot():/boot/httpget.elf
    module_string: phase24-httpget
    module_path: boot():/boot/httpd.elf
    module_string: phase24-httpd
    module_path: boot():/boot/sysinfo.elf
    module_string: phase25-sysinfo
    module_path: boot():/boot/desktop.elf
    module_string: phase26-desktop
